name: Auto Sync Images to ACR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Read YAML and Sync Images
        run: |
          IMAGES_FILE="images.yml"
          while IFS= read -r line; do
            if [[ $line == *":" ]]; then
              REGISTRY=$(echo $line | sed 's/://')
            elif [[ $line == *"- "* ]]; then
              IMAGE=$(echo $line | sed 's/- //')
              echo "Processing $REGISTRY/$IMAGE"

              SOURCE_IMAGE="$REGISTRY/$IMAGE"
              TARGET_IMAGE="${{ secrets.ALIYUN_REGISTRY_URL }}/${{ secrets.ALIYUN_NAMESPACE }}/$IMAGE"
              
              echo "Pulling $SOURCE_IMAGE"
              docker pull $SOURCE_IMAGE
              
              echo "Tagging $SOURCE_IMAGE as $TARGET_IMAGE"
              docker tag $SOURCE_IMAGE $TARGET_IMAGE
              
              echo "Pushing $TARGET_IMAGE"
              docker push $TARGET_IMAGE
            fi
          done < $IMAGES_FILE
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

