name: Auto Sync Images to ACR

on:
  push:
    branches: [ main ]

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Sync Docker images
        run: |
          # 文件路径
          IMAGE_FILE="images.yaml"

          # 读取文件并处理
          while IFS= read -r line
          do
            # 跳过注释行和空行
            [[ "$line" =~ ^#.* ]] || [[ -z "$line" ]] && continue

            # 检测并处理 Docker 注册表标识符
            if [[ "$line" =~ ^(docker.io:|registry.k8s.io:)$ ]]; then
              REPO_PREFIX=${line%%:}
              continue
            fi

            # 处理镜像条目
            if [[ "$line" =~ ^- ]]; then
              IMAGE_NAME=${line#- }

              SOURCE_IMAGE="${REPO_PREFIX}/${IMAGE_NAME}"
              TARGET_IMAGE="${{ secrets.ALIYUN_REGISTRY_URL }}/${{ secrets.ALIYUN_NAMESPACE }}/${IMAGE_NAME#*/}"

              # 拉取镜像
              docker pull "${SOURCE_IMAGE}"

              # 标记镜像
              docker tag "${SOURCE_IMAGE}" "${TARGET_IMAGE}"

              # 推送镜像
              docker push "${TARGET_IMAGE}"
            fi
          done < "${IMAGE_FILE}"

        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

